# Generated by Django 5.2.15 on 2026-07-03 01:36

from django.db import migrations, models


def copy_description_to_issue_summary(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    for ticket in Ticket.objects.filter(issue_summary="").exclude(description=""):
        ticket.issue_summary = ticket.description
        ticket.save(update_fields=["issue_summary"])


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="actual_outcome",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="additional_context",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="expected_outcome",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="issue_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reproduction_steps",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(copy_description_to_issue_summary, migrations.RunPython.noop),
    ]
