# Generated by Django 5.2.15 on 2026-07-03 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_actual_outcome_ticket_additional_context_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("openclaw_workspace", "OpenClaw workspace")],
                        default="openclaw_workspace",
                        max_length=40,
                    ),
                ),
                ("reference", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=220)),
                ("status", models.CharField(default="intake", max_length=40)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("evidence_path", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_operational_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_incidents",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("backend", "reference"),
                        name="unique_operational_incident_reference",
                    ),
                    models.UniqueConstraint(
                        fields=("ticket", "backend"),
                        name="unique_ticket_incident_backend",
                    ),
                ],
            },
        ),
    ]
