# Generated by Django 5.2.15 on 2026-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_operationalincident"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalincident",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("read-only", "Read-only"),
                    ("local-shell", "Local shell"),
                    ("ssh", "SSH"),
                    ("admin", "Admin"),
                    ("physical", "Physical"),
                    ("external-account", "External account"),
                ],
                default="local-shell",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="operationalincident",
            name="actionability",
            field=models.CharField(
                choices=[
                    ("auto-fix", "Auto-fix"),
                    ("guided-fix", "Guided fix"),
                    ("tracked-only", "Tracked only"),
                ],
                default="auto-fix",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="operationalincident",
            name="classification_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="operationalincident",
            name="exposure",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("internal", "Internal"),
                    ("private-channel", "Private channel"),
                    ("public", "Public"),
                    ("user-data", "User data"),
                    ("credential", "Credential"),
                ],
                default="private-channel",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="operationalincident",
            name="p_level",
            field=models.CharField(
                choices=[
                    ("P0", "P0"),
                    ("P1", "P1"),
                    ("P2", "P2"),
                    ("P3", "P3"),
                    ("P4", "P4"),
                ],
                default="P3",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="operationalincident",
            name="risk",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="operationalincident",
            name="human_input_required",
            field=models.CharField(
                choices=[
                    ("no", "No"),
                    ("decision", "Decision"),
                    ("external approval", "External approval"),
                    ("final acceptance", "Final acceptance"),
                ],
                default="no",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="operationalincident",
            name="scope",
            field=models.CharField(
                choices=[
                    ("openclaw-local", "OpenClaw local"),
                    ("openclaw-remote", "OpenClaw remote"),
                    ("owned-software", "Owned software"),
                    ("owned-hardware", "Owned hardware"),
                    ("external-service", "External service"),
                    ("personal-manual", "Personal/manual"),
                ],
                default="owned-software",
                max_length=40,
            ),
        ),
    ]
