# Generated by Django 5.2.15 on 2026-07-05 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tickets", "0004_operationalincident_access_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="visible_to_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave users and groups empty to show this system to all reporters.",
                related_name="visible_systems",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="visible_to_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave users and groups empty to show this system to all reporters.",
                related_name="visible_systems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
