# Generated by Django 5.2.15 on 2026-07-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_operationsagenttoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlaPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("response_minutes", models.PositiveIntegerField()),
                ("resolution_minutes", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SLA policy",
                "verbose_name_plural": "SLA policies",
                "ordering": ["impact"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
