# Generated by Django 5.2.16 on 2026-07-22 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_department_system_default_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="intake_field_values",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="DepartmentIntakeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160)),
                ("help_text", models.CharField(blank=True, max_length=240)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Short text"),
                            ("textarea", "Long text"),
                            ("url", "URL"),
                            ("select", "Select"),
                            ("checkbox", "Checkbox"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True, help_text="One option per line for select fields."
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_fields",
                        to="tickets.department",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("department", "slug"),
                        name="unique_department_intake_field",
                    )
                ],
            },
        ),
    ]
