# Generated by Django 5.2.16 on 2026-07-22 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_ticket_intake_field_values_departmentintakefield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_tic_status_130c04_idx",
        ),
        migrations.AddField(
            model_name="ticket",
            name="board_position",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Operator board ordering within the ticket's current lifecycle status.",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "board_position", "-updated_at"],
                name="tickets_tic_status_ff5b3f_idx",
            ),
        ),
    ]
