# Generated by Django 5.2.16 on 2026-07-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0011_remove_ticket_tickets_tic_status_130c04_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.SlugField(max_length=80)),
                ("external_id", models.CharField(max_length=240)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operational_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_references",
                        to="tickets.operationalincident",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "external_id"],
                "indexes": [
                    models.Index(
                        fields=["provider", "external_id"],
                        name="tickets_ext_provide_c04547_idx",
                    ),
                    models.Index(
                        fields=["ticket", "provider"],
                        name="tickets_ext_ticket__070007_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_id"),
                        name="unique_external_reference",
                    )
                ],
            },
        ),
    ]
